### ISSUE TITLE
Setting of $dataloc 

### ISSUE THREAD

**Issue by rylanchiu** [premgopalan/hgaprec#3]
I am trying to run the code by setting up the Perl code. As the comments in the run.pl said:

set the "prefix" path for the data sets
e.g., if data set resides in /scratch/pgopalan/kdd3/example/movielens
set as follows
my $dataloc = "/scratch/pgopalan/hgaprec/analysis/data";

(1)I am confused by this one. What should I set the address of the dataloc if I, say, put the data on 
"/Users/yobichi/Downloads/hgaprec-master/example/movielens"? By the way, should I set the dataloc variable in run.pl?

(2) The link: http://jmh-recs.cloudapp.net/home/pgopalan/KDD/output, where the readme.txt of output data can not be opened. Where can I see the format of input and out data to get a clearer understanding?

**Comment by premgopalan** [comment]
1. looks like a recent checkin overwrote the prefix path. i'll fix. for now, you would set dataloc, i.e., the prefix to "/scratch/pgopalan/kdd3/example" if the data set resides in /scratch/pgopalan/kdd3/example/movielens. just see how dataloc is used, if you're still unsure.
2. do the files in the examples directory help?

**Comment by rylanchiu** [comment]
1.The first problem has been fixed. Thanks a lot. But there is an error: longest sequence of users with no movies: 0.

2. Sorry, I couldn't understand what each number represent for.
